# This file is not designed to be used a lone, but
# As an addition to './docker-compose.yml' ex: 'docker-compose -f ./docker-compose.yml -f ./docker-compose.deploy.yml up -d'
version: "3"
networks:
  traefik:
    external: true
  hilfling-network: # Used for internal networking

services:
  postgres:
    labels:
      - traefik.enable=false

  hilfling-backend:
    container_name: hilfling-backend
    image: fotogjengen/hilfling-backend
    volumes:
      - ./static-files/:/app/static-files/
    depends_on:
      - postgres
    ports:
      - 8484:8080
    expose:
      - 8080
    networks:
      - traefik
      - hilfling-network
    environment:
      DATABASE_USERNAME: $DATABASE_USERNAME
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_URL:  "jdbc:postgresql://postgres:5432/hilflingdb" #"jdbc:postgresql://postgres:5432/hilflingdb?createDatabaseIfNotExist=true"

    labels:
      - traefik.enable=true
      - traefik.http.routers.hilfling-backend.entrypoints=web # <== Defining the entrypoint for http, **ref: line 30
      - traefik.http.routers.hilfling-backend.entrypoints=websecure # <== Defining the entrypoint for http, **ref: line 30
      - traefik.http.routers.hilfling-backend.rule=Host(`fg-backend.nikzy.no`) # <== Your Domain Name goes here for the http rule
      - traefik.http.routers.hilfling-backend.tls.certresolver=lets-encr # Adds SSL to App
      - traefik.docker.network=traefik

  fg-static:
    #image: fotogjengen/hilfling-static # Don't need to push this to a registry
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.hilfling-rontend.entrypoints=web # <== Defining the entrypoint for http, **ref: line 30
      - traefik.http.routers.hilfling-static.entrypoints=websecure # <== Defining the entrypoint for http, **ref: line 30
      - traefik.http.routers.hilfling-static.rule=Host(`fg-static.nikzy.no`) # <== Your Domain Name goes here for the http rule
      - traefik.http.routers.hilfling-static.tls.certresolver=lets-encr # Adds SSL to App

