# This file uses environment variables
# to override any settings add a file called '.env'
# with new environment variable values
# example: "DATABASE_USERNAME=NikZy"
version: "3"
networks:
  hilfling-network: # Used for internal networking

volumes:
  db-data: # Data volume for the database

services:
  postgres:
    container_name: hilflingdb
    build:
      context: .
      dockerfile: postgres/Dockerfile
    restart: always
    networks:
      - hilfling-network
    volumes:
      - "db-data:/var/lib/postgresql/data" # Database volume
        #- "./postgres/sql:/base-sql" # Think this was init sql schema?
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      # Use env variable if exists, fallback to hilfling
      POSTGRES_USER: ${DATABASE_USERNAME:-hilfling}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      LISTENING_PORT: ${LISTENING_PORT-8080}

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: {$PGADMIN_DEFAULT_EMAIL: -admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: {$PGADMIN_DEFAULT_PASSWORD: -password}
    ports:
      - "5050:80"
    networks:
      - hilfling-network

  fg-static:
    container_name: hilfling-static
    #image: fotogjengen/hilfling-static # Don't need to push this to a registry
    build:
      context: ./static-files
      dockerfile: Dockerfile
    environment:
      NGINX_HOST: ${NGINX_HOST:-fg-static.nikzy.no}
      NGINX_PORT: ${NGINX_PORT:-80}
    ports:
      - 8383:${NGINX_PORT:-80}
    volumes:
      - ./static-files/static/:/usr/share/nginx/html


