version: "3"

networks:
  traefik:
    external: true
  hilfling-network:

services:
  postgres:
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-hilfling}
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
    networks:
      - traefik
      - hilfling-network

  hilfling-backend:
    expose:
      - 8080
    networks:
      - traefik
      - hilfling-network

    labels:
      - traefik.enable=true
      - traefik.http.routers.hilfling-backend.entrypoints=web # <== Defining the entrypoint for http, **ref: line 30
      - traefik.http.routers.hilfling-backend.entrypoints=websecure # <== Defining the entrypoint for http, **ref: line 30
      - traefik.http.routers.hilfling-backend.rule=Host(`fg-backend.nikzy.no`) # <== Your Domain Name goes here for the http rule
      - traefik.http.routers.hilfling-backend.tls.certresolver=lets-encr # Adds SSL to App

  postgres:
    labels:
      - traefik.enable=false
  # Automaticly pulls new images

