version: "2"

services:
  photo-api:
    container_name: photo-api
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8080"
    networks:
      - web

  postgres:
    container_name: photodb
    build:
      context: .
      dockerfile: postgres/Dockerfile
    restart: always
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./postgres/sql:/base-sql"
    ports:
      - "5431:5432"
    networks:
      - web
    environment:
      POSTGRES_PASSWORD: example
networks:
  web:
volumes:
  db-data:
