version: "3"

services:
  hilfling-backend:
    container_name: hilfling-backend
    # image: docker.io/library/hilfing:0.0.1-SNAPSHOT
    build:
      context: .
      dockerfile: Dockerfile
      #    ports:
      #- "8080:8080"
      #    env_file:
      #- variables.env
    networks:
      - hilfling-network
    environment:
      DATABASE_USERNAME: $DATABASE_USERNAME
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_URL:  "jdbc:postgresql://postgres:5432/hilflingdb" #"jdbc:postgresql://postgres:5432/hilflingdb?createDatabaseIfNotExist=true"

  postgres:
    container_name: hilflingdb
    build:
      context: .
      dockerfile: postgres/Dockerfile
    restart: always
    networks:
      - hilfling-network
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./postgres/sql:/base-sql"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-hilfling}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}

networks:
  hilfling-network:


volumes:
  db-data:

