version: "2"

networks:
  traefik:
    external: true
    name: traefik

services:
  photo-api:
    labels:
      - traefik.http.routers.my-container.rule=Host('fg.nikzy.no')
    networks:
      - traefik
