version: "2"

networks:
  traefik:
    external: true

services:
  photo-api:
    labels:
      - traefik.enable = true
      - traefik.docker.network = 'traefik'
      - traefik.http.routers.my-container.rule=Host('fg.nikzy.no')
    networks:
      - traefik
