version: "3"

networks:
  traefik:
    external: true
  hilfling-network: # Used for internal networking

volumes:
  db-data:

services:
  postgres:
    container_name: hilflingdb
    build:
      context: .
      dockerfile: postgres/Dockerfile
    restart: always
    networks:
      - hilfling-network
    volumes:
      - "db-data:/var/lib/postgresql/data" # Database volume
        #- "./postgres/sql:/base-sql" # Think this was init sql schema?
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      # Use env variable if exists, fallback to hilfling
      POSTGRES_USER: ${DATABASE_USERNAME:-hilfling} 
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}

    networks:
      - hilfling-network
    labels:
      - traefik.enable=false

  hilfling-backend:
    container_name: hilfling-backend
    image: fotogjengen/hilfling-backend
    depends_on:
      - postgres
    ports:
      - 8484:8080
    expose:
      - 8080
    networks:
      - traefik
      - hilfling-network
    environment:
      DATABASE_USERNAME: $DATABASE_USERNAME
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_URL:  "jdbc:postgresql://postgres:5432/hilflingdb" #"jdbc:postgresql://postgres:5432/hilflingdb?createDatabaseIfNotExist=true"

    labels:
      - traefik.enable=true
      - traefik.http.routers.hilfling-backend.entrypoints=web # <== Defining the entrypoint for http, **ref: line 30
      - traefik.http.routers.hilfling-backend.entrypoints=websecure # <== Defining the entrypoint for http, **ref: line 30
      - traefik.http.routers.hilfling-backend.rule=Host(`fg-backend.nikzy.no`) # <== Your Domain Name goes here for the http rule
      - traefik.http.routers.hilfling-backend.tls.certresolver=lets-encr # Adds SSL to App


