version: '3.7'

services:
  app:
    container_name: hilfling-app
    ports:
      # TODO: why is this not working on port 8000 
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - hilfling-network
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_USERNAME: hilfling
      DATABASE_PASSWORD: password
      DATABASE_NAME: hilflingdb
      DATABASE_PORT: 5432
      
  postgres:
    container_name: hilflingdb
    build:
      context: .
      dockerfile: postgres/Dockerfile
    restart: always
    volumes:
      - "db-data:/var/lib/postgresql/data" # Database volume
    expose:
      - 5432
    networks:
      - hilfling-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hilfling   # Use POSTGRES_USER instead of DATABASE_USERNAME
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hilflingdb    # Specify the default database
      POSTGRES_HOST_AUTH_METHOD: trust

networks:
  hilfling-network:
    driver: bridge

volumes:
  db-data:
