spring:
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5432/hilflingdb?createDatabaseIfNotExist=true
    username: postgres
    password: example
    driver-class-name: org.postgresql.Driver
  logging:
    level:
      root: error
      me.liuwj.ktorm: debug
      org:
        hibernate:
          type: trace
