server:
  address: ${LISTENING_IP:localhost}
  port: ${LISTENING_PORT:8080}
  error:
    include-message: always
    include-stacktrace: always
    include-exception: true
    include-binding-errors: always
spring:
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    username: ${DATABASE_USERNAME:hilfling}
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/hilflingdb?createDatabaseIfNotExist=true}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}

  logging:
    level:
      root: debug
      me.liuwj.ktorm: debug
      org.springframework.web: DEBUG


  flyway:
    user: ${DATABASE_USERNAME:hilfling}
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/hilflingdb?createDatabaseIfNotExist=true}
    password: ${DATABASE_PASSWORD:password}
    enabled: true
    validate-on-migrate: true
    locations: classpath:/db/migration

  servlet:
    multipart:
      enabled: true # Enable multipart uploads (files)
      file-size-threshold: 2KB
      max-file-size: 50MB
      max-request-size: 60MB
springdoc:
  api-docs:
    #path: "/"
    enabled: true
  swagger-ui:
    path: "/"
static-files:
  img:
    saved-photos-path: "static-files/static/img"

file:
  large-upload-dir: photos/large/
  medium-upload-dir: photos/medium/
  small-upload-dir: photos/small/
#okta: # SECURITY OKTA
#  oauth2:
#    issuer: https://dev-812828.okta.com/oauth2/default
#    client-id: 0oa2lxbl9mygTznZy357
#    audience: api://default
#    groups-claim: groups
#    scopes: 'openid'

