server:
  address:
    - ${LISTENING_IP:backend.localhost}
    - ${LISTENING_IP:localhost}
  port:
    - ${LISTENING_PORT:8000}
    - 8000
  error:
    include-message: always
    include-stacktrace: always
    include-exception: true
    include-binding-errors: always
spring:
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    username: ${secrets.HILFLINGDB_USERNAME:hilfling}
    url: ${secrets.HILFLINGDB_URL_DEV:jdbc:postgresql://hilflingdb.postgres.database.azure.com/hilflingdb-dev}
    password: ${secrets.HILFLINGDB_PASSWORD:password}
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}
  logging:
    level:
      root: debug
      me.liuwj.ktorm: debug
      org.springframework.web: DEBUG
  flyway:
    user: ${secrets.HILFLINGDB_USERNAME:Hilfling}
    url: ${secrets.HILFLINGDB_URL_DEV:jdbc:postgresql://hilflingdb.postgres.database.azure.com/hilflingdb-dev}
    password: ${HILFLINGDB_PASSWORD:wBCJD3qZ7D1I}
    enabled: true
    validate-on-migrate: true
    locations: classpath:/db/migration

  servlet:
    multipart:
      enabled: true # Enable multipart uploads (files)
      file-size-threshold: 2KB
      max-file-size: 50MB
      max-request-size: 60MB
  azure:
    tenant-id:
    client:
      client-id:
      client-secret:
    storage:
      storage-id:
      storage-endpoint:
      container:
      blob-storage:
        connection-string: ${AZURE_STORAGE_CONNECTION_STRING:DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;}

springdoc:
  api-docs:
    #path: "/"
    enabled: true
  swagger-ui:
    path: "/"

# Doesn't currently work?
static-files:
  img:
    saved-photos-path: "static-files/static/img"

file:
  large-upload-dir: photos/large/
  medium-upload-dir: photos/medium/
  small-upload-dir: photos/small/
#okta: # SECURITY OKTA
#  oauth2:
#    issuer: https://dev-812828.okta.com/oauth2/default
#    client-id: 0oa2lxbl9mygTznZy357
#    audience: api://default
#    groups-claim: groups
#    scopes: 'openid'

