http:
  routers:
    backend-router:
      rule: Host(`localhost`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      service: api@internal
      entryPoints:
        - web

  services:
    backend-service:
      loadBalancer:
        servers:
          - url: "http://hilfling-backend1.norwayeast.azurecontainer.io:8000"
          - url: "http://hilfling-backend2.norwayeast.azurecontainer.io:8000"
          - url: "http://hilfling-backend3.norwayeast.azurecontainer.io:8000"
          - url: "http://hilfling-backend4.norwayeast.azurecontainer.io:8000"
