http:
  routers:
    backend-router:
      rule: "Host(`hilfling-traefik.norwayeast.azurecontainer.io`)"
      service: backend-service
      entryPoints:
        - web
        - websecure

  services:
    backend-service:
      loadBalancer:
        servers:
          - url: "http://hilfling-backend1.norwayeast.azurecontainer.io:8000"
          - url: "http://hilfling-backend2.norwayeast.azurecontainer.io:8000"
          - url: "http://hilfling-backend3.norwayeast.azurecontainer.io:8000"
          - url: "http://hilfling-backend4.norwayeast.azurecontainer.io:8000"
