# Static configuration for Traefik

api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

certificatesResolvers:
  mytlschallenge:
    acme:
      email: your_email@example.com
      storage: acme.json
      httpChallenge:
        entryPoint: web
