# CI-CD
# Runs on push to master
name: CI-CD

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          # Install Docker Compose
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

          # Create a symbolic link to ensure it's accessible globally
          sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

          # Verify Docker Compose installation
          docker-compose --version

      - name: Build docker stack
        run: |
          docker network create traefik
          docker-compose -f docker-compose.yml -f docker-compose.test.yml up run-tests

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.2.1
        with:
          tags: fotogjengen/hilfling-backend:latest
          push: true

      - name: "Package app outside docker"
        run: "mvn clean package spring-boot:repackage"

      - name: "Publish package to Github Releases"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: ./target/*

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ktlint with reviewdog
        uses: ScaCap/action-ktlint@1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: error
          reporter: github-pr-check
          fail_on_error: false
          relative: true
