name: Build and deploy JAR app to Azure Container App - hilfling-backend

on:
  push:
    branches:
      - feature/fg-137
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest



    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx for multi-platform builds (optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build and Push Docker Image to ACR
      - name: Build and push Docker image to ACR
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/hilfling-backend:${{ github.sha }} .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/hilfling-backend:${{ github.sha }}


      - name: Delete existing Azure Container Apps (if any)
        run: |
          az containerapp delete \
            --name hilfling-backend1 \
            --resource-group hilfling-backend_group \
            --yes || true

      - name: Deploy to Azure Container App
        run: |
          az containerapp create \
          --name hilfling-backend1 \
          --resource-group hilfling-backend_group \
          --environment hilfling-environment \
          --image ${{ secrets.ACR_LOGIN_SERVER }}/hilfling-backend:${{ github.sha }} \
          --cpu 1 --memory 2Gi \
          --env-vars DATABASE_USERNAME=${{ secrets.HILFLINGDB_USERNAME }} \
          DATABASE_URL=${{ secrets.HILFLINGDB_URL_DEV }} \
          DATABASE_PASSWORD=${{ secrets.HILFLINGDB_PASSWORD }} \
          --ingress 'external' \
          --target-port 8000 \
          

